// Generates mobile/src/gbkTable.ts from Node's ICU GBK decoder.
// Output: fixed-width 4-hex-digit entries indexed by
//   idx = (lead - 0x81) * 190 + (trail <= 0x7F ? trail - 0x40 : trail - 0x41)
// A zero entry marks an unassigned GBK code.
import { writeFileSync } from 'node:fs';

const LEAD_MIN = 0x81;
const LEAD_MAX = 0xFE;
const TRAIL_MIN = 0x40;
const TRAIL_MAX = 0xFE;

// GBK trail ranges: 0x40-0x7E (63 slots) then 0x80-0xFE (127 slots) = 190.
function idxOf(lead, trail) {
  return (lead - LEAD_MIN) * 190 + (trail <= 0x7E ? trail - 0x40 : trail - 0x41);
}

const total = (LEAD_MAX - LEAD_MIN + 1) * 190;
const table = new Array(total).fill(0);
const decoder = new TextDecoder('gbk');
let assigned = 0;

const bytes = new Uint8Array(2);
for (let lead = LEAD_MIN; lead <= LEAD_MAX; lead += 1) {
  for (let trail = TRAIL_MIN; trail <= TRAIL_MAX; trail += 1) {
    if (trail === 0x7F) continue;
    bytes[0] = lead;
    bytes[1] = trail;
    const text = decoder.decode(bytes, { stream: false });
    if (text === '\uFFFD') continue;
    const code = text.codePointAt(0);
    if (code === undefined || text.length !== 1) continue;
    table[idxOf(lead, trail)] = code;
    assigned += 1;
  }
}

const packed = table.map(code => code.toString(16).padStart(4, '0')).join('');
const header = `// GENERATED by scripts/genGbkTable.mjs - do not edit by hand.
// GBK double-byte decode table: ${assigned} assigned codes, ${total} slots.
// Index: (lead - 0x81) * 190 + (trail <= 0x7F ? trail - 0x40 : trail - 0x41).
// Each slot is a fixed 4-hex-digit Unicode code point; 0000 = unassigned.
export const GBK_TABLE_VERSION = 'gbk-2026-09-27';
export const GBK_TABLE = '${packed}';
`;
writeFileSync(new URL('../mobile/src/gbkTable.ts', import.meta.url), header);
console.log(`gbk table written: ${assigned} assigned codes, ${packed.length} chars`);
